#aws:
#  bucket:
#    access_key_id:
#    secret_access_key:
#    region: eu-central-1
#    name: ebookjava5
#    path: https://ebookjava5.s3.eu-central-1.amazonaws.com/
#
#server:
#  port: 4000
#  error:
#    include-message: always